#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_FT5426)	+=  focaltech_core.o
obj-$(CONFIG_TOUCHSCREEN_FT5426)	+=  focaltech_esdcheck.o
obj-$(CONFIG_TOUCHSCREEN_FT5426)	+=  focaltech_ex_mode.o
obj-$(CONFIG_TOUCHSCREEN_FT5426)	+=  focaltech_gesture.o
obj-$(CONFIG_TOUCHSCREEN_FT5426)   +=  focaltech_point_report_check.o
obj-$(CONFIG_TOUCHSCREEN_FT5426)   +=  focaltech_i2c.o
obj-$(CONFIG_TOUCHSCREEN_FT5426)   +=  focaltech_sensor.o
