# SPDX-License-Identifier: GPL-2.0

# required for overlay support
DTC_FLAGS += -@

dtb-y += ext-gpio.dtbo
dtb-y += ext-i2c4.dtbo
dtb-y += ext-spi5.dtbo
dtb-y += ext-uart4.dtbo
dtb-y += display-mipi.dtbo
dtb-y += display-mipi-ph720128t003.dtbo
dtb-y += display-mipi-tft7201280.dtbo
dtb-y += display-mipi-tft8001280.dtbo
dtb-y += camera-ov5640.dtbo
