# SPDX-License-Identifier: GPL-2.0

# required for overlay support
DTC_FLAGS += -@

dtb-y += camera-ov5640.dtbo
dtb-y += ext-gpio.dtbo
dtb-y += ext-i2c3.dtbo
dtb-y += ext-spi3.dtbo
dtb-y += ext-wm8960.dtbo
dtb-y += display-mipi.dtbo
dtb-y += display-mipi-ph720128t003.dtbo
