# SPDX-License-Identifier: GPL-2.0

# required for overlay support
DTC_FLAGS += -@

dtb-y += maaxboard-8ulp-ext-gpio.dtbo
dtb-y += maaxboard-8ulp-ext-spi.dtbo
dtb-y += maaxboard-8ulp-ext-i2c.dtbo
dtb-y += maaxboard-8ulp-ext-uart.dtbo
dtb-y += maaxboard-8ulp-mipi.dtbo
dtb-y += maaxboard-8ulp-cam.dtbo
