# SPDX-License-Identifier: GPL-2.0

# required for overlay support
DTC_FLAGS += -@

dtb-y += maaxboard-nano-mipi.dtbo
dtb-y += maaxboard-nano-audio.dtbo
dtb-y += maaxboard-nano-mic.dtbo
dtb-y += maaxboard-nano-ov5640.dtbo
dtb-y += maaxboard-nano-ext-gpio.dtbo
dtb-y += maaxboard-nano-ext-i2c.dtbo
dtb-y += maaxboard-nano-ext-pwm.dtbo
dtb-y += maaxboard-nano-ext-spi.dtbo
dtb-y += maaxboard-nano-ext-uart4.dtbo
dtb-y += maaxboard-nano-ext-sai3.dtbo
