# SPDX-License-Identifier: GPL-2.0

# required for overlay support
DTC_FLAGS += -@

# DTB Overlays for Maaxboard-Mini
dtb-y += display-mipi.dtbo
dtb-y += ext-gpio.dtbo
dtb-y += ext-i2c2.dtbo
dtb-y += ext-i2c3.dtbo
dtb-y += ext-pwm1.dtbo
dtb-y += ext-pwm2.dtbo
dtb-y += ext-pwm3.dtbo
dtb-y += ext-spi1.dtbo
dtb-y += ext-uart2.dtbo
dtb-y += usb0-device.dtbo
